#492 Sonar fixes
Netcentric/accesscontroltool pull request #502
Opened 2020-10-19 15:15 UTC by ghenzler

2020-10-19 15:45 UTC, kwin requested changes
I think the Sonarcloud issues are rather false positives and should just be disabled with annotations (https://github.com/SonarSource/sonar-java/blob/2e3b7d25cebac51d5040d30dc3048c2f575d6e92/its/plugin/projects/suppress-warnings/src/main/java/SuppressWarningsAtMethodLevelWithRule.java#L4)

2020-10-19 15:45 UTC, kwin commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/ui/AcToolUiService.java
> +                escapeHtml4(reqParams.configurationRootPath), reqParams.basePaths);
why do you escape for HTML parsers in a log? A log line is never evaluated as HTML IMHO

2020-10-19 15:45 UTC, kwin commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/ui/AcToolUiService.java
> +            pw.println("Applied AC Tool config from " + escapeHtml4(reqParams.configurationRootPath) + ":\n" + msg);
This is plain text and therefore should not contain any HTML escaping!

2020-10-20 06:35 UTC, kwin commented
Still one FP: https://sonarcloud.io/project/issues?id=Netcentric_accesscontroltool&open=AXVCFo2RKPqjJP9f4pZJ&pullRequest=502&resolved=false&types=VULNERABILITY

Let us ignore javasecurity:S5145 as well.

2020-10-20 08:36 UTC, ghenzler commented
@kwin For some reason Sonar still reports on `javasecurity:S5145` even thought it should be suppressed via 9cf21cb47b08ee1d8f883f74faeae00c82bb25af

2020-10-20 08:43 UTC, merged