Reduce dependencies
Netcentric/accesscontroltool pull request #603
Opened 2021-10-15 11:40 UTC by ghenzler

Closes #602

2021-10-15 11:45 UTC, kwin requested changes
We should adjust https://github.com/Netcentric/accesscontroltool/blob/develop/target-osgi-environment/maximum-environment/pom.xml to check that it runs without those dependencies!

2021-10-15 11:45 UTC, kwin commented on accesscontroltool-bundle/bnd.bnd
> +org.apache.sling.commons.scheduler.*;resolution:=optional,\
we might need to reconsider optional imports: https://github.com/adobe/aem-core-wcm-components/issues/1872

2021-10-15 11:48 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
dependency-checks considers this version vulnerable

2021-10-18 09:29 UTC, ghenzler commented on accesscontroltool-bundle/bnd.bnd
> +org.apache.sling.commons.scheduler.*;resolution:=optional,\
I see, also interesting the discussion on [Felix mailing list](https://lists.apache.org/thread.html/r20cceffd651904eda7e6512b2699b5381ab8044e352bb27cb14e9964%40%3Cusers.felix.apache.org%3E) - for `org.apache.sling.commons.scheduler` it should work reliably though, in AEM it starts at start level 19 (before the AC Tool is wired), in Sling it comes slightly later ([start level 20](https://github.com/apache/sling-org-apache-sling-starter/blob/5e9f0fc352d0a9ea855409d4a90283f4397f006b/src/main/features/base.json#L70), yet it should still be ok)

2021-10-18 13:15 UTC, ghenzler commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
this is currently using the same version as https://github.com/apache/sling-org-apache-sling-scripting-jsp-api/blob/8c36e309e7eae7277882445727733b400026de59/pom.xml#L48 - checking if I can get a better version without vulnerability

2021-10-18 13:26 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
by embedding it we have to take care of that vulnerabilities don't affect us, if just using the provided one Adobe does that for us

2021-10-18 13:48 UTC, ghenzler commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
0a18191 fixes this and uses the latest dependency (the group id changed from `jsp-api` to `tomcat-jsp-api`, that wasn't immediately obvious)

2021-10-18 13:50 UTC, ghenzler commented
> We should adjust https://github.com/Netcentric/accesscontroltool/blob/develop/target-osgi-environment/maximum-environment/pom.xml to check that it runs without those dependencies!

d30e5bf removes scripting dependencies in min environment (the max env didn't include them)

2021-10-18 13:53 UTC, ghenzler commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
turns out that the current version still has one vulnerability left: CVE-2020-8022

2021-10-18 14:12 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
This is a false-positive: https://github.com/Netcentric/accesscontroltool/issues/596#issuecomment-922831860

2021-10-18 17:28 UTC, kwin commented on accesscontroltool-bundle/bnd.bnd
> +-contract: !JavaServlet,*
AEM 6.5.x only provides support for Servlet Spec 3.1 while Tomcat 9 is for Servlet Spec 4.0 (https://tomcat.apache.org/whichversion.html), we should therefore stick to Tomcat 8, the require capability is there for a reason in Tomcat 9!

2021-10-18 18:35 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +        <tomcat.libs.version>10.0.12</tomcat.libs.version>
Currently documentation states that we support EL 2.2 (https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#expressions). What has changed in 4.0? Is that really fully backwards compatible?

2021-10-18 18:37 UTC, ghenzler commented on accesscontroltool-bundle/bnd.bnd
> +-contract: !JavaServlet,*
we currently don't have the `Require-Capability` for the servlet API, the header comes from the embedded dependency (that is only embedded because fo the EL functionality)

2021-10-18 18:45 UTC, kwin commented on accesscontroltool-bundle/bnd.bnd
> +-contract: !JavaServlet,*
we depend on this dependency having the contract, so transitively we also depend on the capability!

2021-10-18 19:06 UTC, ghenzler commented on accesscontroltool-bundle/pom.xml
> +        <tomcat.libs.version>10.0.12</tomcat.libs.version>
The unit tests pass... if even, only edge cases could cause a problem. 

Also more generally, as EL is used broadly in a huge amount of systems, I would assume new versions are carefully tested to be backwards-compatible.

2021-10-18 20:26 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +        <tomcat.libs.version>10.0.12</tomcat.libs.version>
We need at least an update of the documentation that we now support EL 4.0 with the according link.

2021-10-19 07:21 UTC, ghenzler commented on accesscontroltool-bundle/pom.xml
> +        <tomcat.libs.version>10.0.12</tomcat.libs.version>
Updated doc in ba2634b

2021-10-19 07:25 UTC, kwin commented on accesscontroltool-bundle/pom.xml
> +          <version>6.0.14</version>
No longer relevant, as JSP dependency has  been removed.

2021-10-19 07:25 UTC, kwin approved these changes

2021-10-19 07:26 UTC, merged