Improve documentation around installation of AC Tool
Netcentric/accesscontroltool pull request #607
Opened 2021-10-29 11:36 UTC by ghenzler

Closes #606

2021-11-04 07:50 UTC, kwin requested changes

2021-11-04 07:50 UTC, kwin commented on README.md
> +For properly integrating the AC Tool in the development process see [Installation](docs/Installation.md).
the development process -> your own deployment package

2021-11-04 07:50 UTC, kwin commented on README.md
> +There is a Felix Web Console plugin (at `/system/console/actool`) as well as a Touch UI console (at `/mnt/overlay/netcentric/actool/content/overview.html`) to apply configurations and to inspect prev
```suggestion
There is a Felix Web Console plugin (at `/system/console/actool`) as well as a Touch UI console (at `/mnt/overlay/netcentric/actool/content/overview.html`) to apply configurations and to inspect previous executions of the tool. Additionally there is a [JMX interface](docs/Jmx.md) for some advanced use cases.
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +Due to the different nature of on-premise and cloud service infrastructure setup, the maven setup for installation of the two packages is slightly different (while the AC Tool configuration as such i
```suggestion
Due to the different nature of on-premise and cloud service infrastructure setup, the Maven setup for installation of the two packages is slightly different (while the AC Tool configuration as such is compatible with both setups and can usually easily be lifted from on-premise to the cloud service).
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +For AEM 6.4/6.5 use the following appraoch:
```suggestion
For AEM 6.4/6.5 use the following approach:
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +* Use a complete package that contains all project-related packages as sub package (hence in `/etc/packages`)
```suggestion
* Use a [container package](https://jackrabbit.apache.org/filevault/packagetypes.html) that contains all project-related packages as sub package (hence in `/etc/packages`)
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +* Include the `accesscontroltool-package` *without* the `cloud` classifier (this has the [Sling Installer Provider Install Hook](https://sling.apache.org/documentation/bundles/installer-provider-inst
```suggestion
* Include the `accesscontroltool-package` *without* the `cloud` classifier (this leverages the [Sling Installer Provider Install Hook](https://sling.apache.org/documentation/bundles/installer-provider-installhook.html))
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +Use the package with the GAV
There is no V below. Rather use "Maven coordinates" or say "group id and artifact id"

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +For AEMaaCS use the use the following appraoch:
```suggestion
For AEMaaCS use the use the following approach:
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +* Use an `all` package that contains all project-related packages as embedds (hence in `/apps`)
```suggestion
* Use a  container package that contains all project-related packages as embedded artifacts (hence in `/apps`)
```

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +Use the package with the GAV and classifier `cloud`:
Again no V (version) below

2021-11-04 07:50 UTC, kwin commented on docs/Installation.md
> +Install it afterwards e.g. via AEM's package manager.
```suggestion
Install it afterwards e.g. via AEM's package manager or embed it in your container package.
```

2021-11-08 10:16 UTC, ghenzler commented
@kwin thanks for the review, I incorporated the suggestions in 47472bff

2021-11-08 14:16 UTC, kwin approved these changes

2021-11-08 17:15 UTC, merged