Also interpret cost JSON object in case it is returned by oak search engine
Netcentric/accesscontroltool pull request #731
Opened 2024-06-13 08:24 UTC by ghenzler

Closes #730

2024-06-13 09:13 UTC, kwin requested changes

2024-06-13 09:13 UTC, kwin commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
> +        String costJsonStr = plan.substring(plan.lastIndexOf('{'));
Probably we should log the JSON (on debug/verbose level) in case it changes in the future, so that we can more easily come up with a fix.

2024-06-13 09:13 UTC, kwin commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
> +        JsonNode sNode = node.get("s");
We need some more null checks here and a unit test with invalid JSON.

2024-06-13 09:13 UTC, kwin commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
> +        double cost = sNode.isContainerNode() ? sNode.get("perExecution").asDouble(Double.MAX_VALUE) : sNode.asDouble(Double.MAX_VALUE);
let us null check sNode.get("perExecution") as well.

2024-06-14 15:20 UTC, ghenzler commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
>              }
no matter what exception is thrown this warning should be shown

2024-06-14 15:22 UTC, ghenzler commented on accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
> +        String costJsonStr = StringUtils.substringAfter(plan, "cost:");
just checking for `{` is also very unsafe - conceptually better to check for the string after `cost:`.  (`plan.substring(plan.lastIndexOf('{'))` returned only parts of the cost json)

2024-06-14 17:31 UTC, kwin approved these changes
Thanks for the fixes, looks good now.

2024-06-17 06:39 UTC, merged