751 Expose isEmpty and isBlank for EL evaluation
Netcentric/accesscontroltool pull request #752
Opened 2024-07-15 13:46 UTC by Positronic-Brain

This would implement [issue #751](https://github.com/Netcentric/accesscontroltool/issues/751)

2024-07-15 16:00 UTC, kwin requested changes
Looks good in general, but:
- requires a minor version upgrade (please adjust the pom.xml accordingly)
- requires some info on documentation since when which method is supported.

2024-07-15 16:00 UTC, kwin commented on docs/AdvancedFeatures.md
> +`isBlank(String str)` | [`StringUtils.isBlank(...)`](https://commons.apache.org/proper/commons-lang/javadocs/api-3.3/org/apache/commons/lang3/StringUtils.html#isBlank(java.lang.CharSequence))
You should probably add a `Since` column indicating the version since when it is supported.

2024-07-16 08:38 UTC, ghenzler commented
there isn't much that speaks against linking these two methods, but we could also just document the `empty` operator that EL provides out of the box (see https://docs.oracle.com/cd/E17802_01/j2ee/j2ee/1.4/docs/tutorial-update6/doc/JSPIntro7.html#wp71089)

2024-07-16 08:44 UTC, Positronic-Brain commented
Yeah, empty is a bit redundant, but since I was already exposing "isBlank" I decided to add its related method for consistency.

2024-07-16 09:21 UTC, Positronic-Brain commented on docs/AdvancedFeatures.md
> +`isBlank(String str)` | [`StringUtils.isBlank(...)`](https://commons.apache.org/proper/commons-lang/javadocs/api-3.3/org/apache/commons/lang3/StringUtils.html#isBlank(java.lang.CharSequence))
Fixed. I also sorted methods alphabetically because it was bugging me out,

2024-07-16 09:33 UTC, ghenzler commented
@Positronic-Brain  so I just checked and `empty '   '` really does not return true (which I thought would be the case for EL). So fair enough to add the two methods, but I probably would also add https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#defaultIfBlank-T-T- then (as we have `defaultIfEmpty(..)` already)

2024-07-16 09:39 UTC, Positronic-Brain commented
> @Positronic-Brain so I just checked and `empty ' '` really does not return true (which I thought would be the case for EL). So fair enough to add the two methods, but I probably would also add https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#defaultIfBlank-T-T- then (as we have `defaultIfEmpty(..)` already)

Sounds reasonable. Will do.

2024-07-16 15:16 UTC, kwin approved these changes
LGTM now. Thanks a lot.

2024-07-16 17:06 UTC, merged